title: AHSubs
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4
twitter_username: jekyllrb
permalink: /:slug/
github_username:  jekyll
theme: forty_jekyll_theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-paginate-v2
  - jekyll-seo-tag
markdown: kramdown
sass:
  style: compressed
include:
 - _pages
# Pagination
pagination:
 enabled: true
 debug: true
 collections: 'posts'
 per_page: 2
 permalink: '/page/:num/'
 title: ':title - page :num'
 limit: 0
 sort_field: date
 sort_reverse: true
 trail: 
   before: 2
   after: 2
 extension: html
 indexpage: 'main'
autopages:
  enabled: false
  layouts:
    - 'allposts.html'
  title: 'Post nella categoria :cat'
  permalink: '/sez/:cat'
  slugify:
    mode: 'default'
    case: 'true'
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/