name: Generazione Sito On Push
on:
 push:
  branches:
  - master

jobs:
  github-pages:
    name: Sito
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: helaili/jekyll-action@2.0.5
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
