name: Deploy
on:
 push:
  branches:
  - master
 scheudle:
  - cron: "0 0 * * *"

jobs:
  github-pages:
    name: Sito
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: helaili/jekyll-action@v2
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
